sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hgpu20/VlYN+DkYSlC1zlHFxrQxUi93cDNUxly5AjUpQyIEm35Kmfv6+YMJ/UFyxSvS4nMjRINjztvoTJazwcGcQfCd4HhiJuDaeYcCHcK2AtCSHwgG1ODWRIxHGnud343GhKsMTOsDoCTF1Mdn9m8b/RkEroXCB5mNsT3VoqMa3HeaX/lxwIqbGaPONh4O43JLli/Lh3CqDlsuFztL6ILyPX0eQTZ3krVrfwBjMoHKVeM4VWhkKSllrekFrrDVceYOCSQXy+54oDIHhMy3TWI5MY2WDMHB6gSfQpzSOutyCn30lGebW0xGe+O/tM97l+VDkPdRt4u2WIA2tRXKR0Lr5PiiuXI83tFMCPppRcTGfvAFk7AAssCftnbzL/m8e0SkWSFx3S+VoqsOpLXVYT+U5yrYExekWGuCQ6DVBMfTOZhtJqfbL16QfrsH3WEBpQmpNgRjXUKrDJqD0XC/eInhwHZ008nn59ltwqFBGFMEXRg92N1+uhvJhTAq5l3MdDlQYEK0NO8gbxpI02OVMweSnKiSSLv1mSvpdx+6CdV7ShZxdUAvA6wQX27F1q2jRLm5y/U68YoxBAv+vYHj7jZ9Hvaht9YbS07fxle3OxzrOtovXI5ycEKFnLh1QsMuYvDRqMme2oVgG5Va0nJp1e83IuUHh1bWXrdbkU8RPRQM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Luck-or-Cunning-as-the-Main-Means-of-Organic-Modification_4967
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy